name: Test
on: ["pull_request"]
jobs:
  iscodeclean:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Code Cleanliness
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run Prettier Test
        run: npx prettier --check "src/**/*.js"
      - name: Run Lint Test
        run: |
          # TODO this takes 1-2 mins to install, run eslint w/o installing
          # everything
          npm install
          npm run test:lint
  cypress-run:
    name: Cypress Integration Tests (Browser Tests)
    needs: iscodeclean
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: http://localhost:6001
          wait-on-timeout: 120
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
